In [12]:
import pandas as pd
import numpy as np
import datetime
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn import preprocessing

DailyDf = pd.read_csv('/Users/josevans/Library/Mobile Documents/com~apple~CloudDocs/Python files/BTCDailyEngineered.csv', index_col='date', parse_dates=True)
DailyDf.head()

,close,high,low,open,volume,realised_vol,heavy_volume,low_volume,above_avg_volume,below_avg_volume,...,binary_gold_cross_100_200,binary_death_cross_100_200,ydaybinary_gold_cross_8_13,ydaybinary_death_cross_8_13,ydaybinary_gold_cross_20_50,ydaybinary_death_cross_20_50,ydaybinary_gold_cross_50_100,ydaybinary_death_cross_50_100,ydaybinary_gold_cross_100_200,ydaybinary_death_cross_100_200
date,,,,,,,,,,,,,,,,,,,,,
2013-01-03,13.09,13.19,12.98,13.12,1840.85,NaN,0,0,0,0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-04,13.19,13.26,12.96,13.09,3320.97,NaN,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-01-05,13.19,13.24,12.84,13.12,2700.25,NaN,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-01-06,13.15,13.19,13.03,13.19,1463.54,NaN,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-01-07,13.15,13.15,13.06,13.11,453.56,NaN,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
cols_to_drop = ['close', 'high', 'low', 'open']+[col for col in DailyDf.columns if 'later' in col]

In [5]:
cols_to_drop

['close',
 'high',
 'low',
 'open',
 '%chg_1_days_later',
 '%chg_2_days_later',
 '%chg_3_days_later',
 '%chg_4_days_later',
 '%chg_5_days_later',
 '%chg_8_days_later',
 '%chg_10_days_later',
 '%chg_13_days_later',
 '%chg_15_days_later',
 '%chg_20_days_later',
 '%chg_30_days_later',
 '%chg_35_days_later',
 '%chg_40_days_later',
 '%chg_45_days_later']

In [8]:
TrainDf = DailyDf.drop(cols_to_drop, axis=1).dropna()

In [9]:
TrainDf.head()

,volume,realised_vol,heavy_volume,low_volume,above_avg_volume,below_avg_volume,avg_volume,dayRangeAbs,dayRange%,binaryNR7,...,binary_gold_cross_100_200,binary_death_cross_100_200,ydaybinary_gold_cross_8_13,ydaybinary_death_cross_8_13,ydaybinary_gold_cross_20_50,ydaybinary_death_cross_20_50,ydaybinary_gold_cross_50_100,ydaybinary_death_cross_50_100,ydaybinary_gold_cross_100_200,ydaybinary_death_cross_100_200
date,,,,,,,,,,,,,,,,,,,,,
2013-07-21,4451.47,92.359931,0,0,0,1,0,2.80,3.236620,1,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-07-22,2907.86,92.484024,0,1,0,1,0,2.74,3.222771,1,...,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-07-23,8294.02,92.412639,0,0,0,1,0,4.08,4.759127,0,...,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2013-07-24,13038.50,92.580649,0,0,0,0,1,6.88,8.038322,0,...,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2013-07-25,9276.42,92.771049,0,0,0,0,1,2.75,3.165285,0,...,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
TrainDf.dtypes

volume                            float64
realised_vol                      float64
heavy_volume                        int64
low_volume                          int64
above_avg_volume                    int64
                                   ...
ydaybinary_death_cross_20_50      float64
ydaybinary_gold_cross_50_100      float64
ydaybinary_death_cross_50_100     float64
ydaybinary_gold_cross_100_200     float64
ydaybinary_death_cross_100_200    float64
Length: 123, dtype: object

In [42]:
col_names = TrainDf.columns

cols_to_be_scaled = [col for col in TrainDf.columns if ((TrainDf[col].min() != 0) and (TrainDf[col].max() != 1))]

scaler = preprocessing.StandardScaler()

ScaledDf = scaler.fit_transform(TrainDf[cols_to_be_scaled])

ScaledDf = pd.DataFrame(ScaledDf, columns=cols_to_be_scaled, index=TrainDf.index)

newdf = ScaledDf.merge(TrainDf[TrainDf.columns.difference(cols_to_be_scaled)], on=TrainDf.index).set_index('key_0')

newdf.head()

,volume,realised_vol,dayRangeAbs,dayRange%,RSI,macd_signal_roc,distance_from_SMA5,distance_from_SMA8,distance_from_SMA10,distance_from_SMA13,...,ydaybinary_death_cross_50_100,ydaybinary_death_cross_8_13,ydaybinary_gold_cross_100_200,ydaybinary_gold_cross_20_50,ydaybinary_gold_cross_50_100,ydaybinary_gold_cross_8_13,ydaybinaryaboveupperboll,ydaybinarybelowlowerboll,ydaysenkou_binary_downtrend,ydaysenkou_binary_uptrend
key_0,,,,,,,,,,,,,,,,,,,,,
2013-07-21,-0.782225,1.004975,-0.559170,-0.651141,0.956237,-0.016091,-0.796343,-0.883601,-0.767523,-0.369964,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2013-07-22,-0.814741,1.008800,-0.559286,-0.653437,1.042559,-0.009007,-0.294868,-0.600886,-0.613367,-0.367283,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2013-07-23,-0.701285,1.006599,-0.556689,-0.398761,0.687549,-0.007720,-0.106454,-0.563473,-0.596277,-0.513219,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2013-07-24,-0.601346,1.011779,-0.551261,0.144816,0.734919,-0.001587,0.159563,-0.160565,-0.311999,-0.342521,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2013-07-25,-0.680591,1.017648,-0.559267,-0.662966,0.774760,0.002465,0.427819,0.175191,-0.063576,-0.169267,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [21]:
from sklearn.model_selection import train_test_split

X = newdf
y = DailyDf.dropna()['%chg_1_days_later']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

,volume,realised_vol,dayRangeAbs,dayRange%,RSI,macd_signal_roc,distance_from_SMA5,distance_from_SMA8,distance_from_SMA10,distance_from_SMA13,...,distance_from_EMA13,distance_from_EMA15,distance_from_EMA20,distance_from_EMA30,distance_from_EMA35,distance_from_EMA40,distance_from_EMA45,distance_from_EMA50,distance_from_EMA100,distance_from_EMA200
date,,,,,,,,,,,,,,,,,,,,,
2013-07-21,4451.47,92.359931,2.80,3.236620,71.300870,-0.367298,-3.220667,-4.827721,-4.677569,-1.969443,...,-2.152159,-2.191363,-2.793503,-5.156448,-6.450756,-7.649785,-8.696908,-9.567805,-10.153018,5.870175
2013-07-22,2907.86,92.484024,2.74,3.222771,72.880168,-0.211971,-0.940677,-3.053209,-3.550223,-1.946000,...,-0.968518,-1.023258,-1.609736,-3.905705,-5.183475,-6.378059,-7.429787,-8.311379,-9.046784,6.903948
2013-07-23,8294.02,92.412639,4.08,4.759127,66.385135,-0.183752,-0.084041,-2.818380,-3.425245,-3.222159,...,-1.158374,-1.230099,-1.801704,-4.010008,-5.255600,-6.430068,-7.472089,-8.352125,-9.227182,6.424639
2013-07-24,13038.50,92.580649,6.88,8.038322,67.251783,-0.049277,1.125424,-0.289456,-1.346309,-1.729472,...,0.372712,0.316798,-0.197823,-2.307301,-3.528365,-4.692770,-5.735297,-6.622886,-7.621767,8.052842
2013-07-25,9276.42,92.771049,2.75,3.165285,67.980692,0.039561,2.345070,1.817972,0.470422,-0.214423,...,1.738749,1.726130,1.314115,-0.645721,-1.825895,-2.967471,-4.000447,-4.887612,-5.978968,9.734254

In [43]:
IntraDf = pd.read_csv('/Users/josevans/Library/Mobile Documents/com~apple~CloudDocs/Python files/BTCintraday.csv')
IntraDf.head()

,date,high,open,tradesDone,close,low,volume
0,2020-08-06 00:00:00+00:00,11757.194678,11757.194678,7.0,11732.419353,11732.419353,4.871922
1,2020-08-06 00:01:00+00:00,11753.930698,11751.933918,3.0,11753.930698,11751.744793,0.000888
2,2020-08-06 00:02:00+00:00,11785.133323,11766.188451,12.0,11781.654055,11766.188451,0.051744
3,2020-08-06 00:03:00+00:00,11787.920784,11776.823827,6.0,11784.589509,11776.823827,1.018644
4,2020-08-06 00:04:00+00:00,11787.542442,11787.542442,5.0,11784.217781,11782.047472,0.014016